spring:
  datasource:
    url: jdbc:mysql://database-1.cuax43rzes2d.ap-northeast-2.rds.amazonaws.com:3306/banguDB
    username: admin
    password: alstjs3369
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

  profiles:
    include: jwt

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  url:
    base: http://localhost:8080

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect

logging:
  level:
    org.hibernate.type: trace

jwt:
  secret: bWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGktbWUtaHllb25pYy1teS1wbGk=

social:
  kakao:
    client-id: ed809cae6b46a0ddeda9be7f2aa25d0a
    redirect: /oauth/kakao/redirect
  url:
    login: https://kauth.kakao.com/oauth/authorize
    token: https://kauth.kakao.com/oauth/token
    profile: https://kapi.kakao.com/v2/user/me
    unlink: https://kapi.kakao.com/v1/user/unlink
